//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.API.DGA.MIL.DOC.TEST.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.DocumentAttachment = new HashSet<DocumentAttachment>();
            this.DocumentProcess = new HashSet<DocumentProcess>();
            this.DocumentReference = new HashSet<DocumentReference>();
        }
    
        public int Id { get; set; }
        public string BookId { get; set; }
        public string ProcessId { get; set; }
        public string No { get; set; }
        public string From { get; set; }
        public string Type { get; set; }
        public string Date { get; set; }
        public string Subject { get; set; }
        public string Speed { get; set; }
        public string Secret { get; set; }
        public string Description { get; set; }
        public string MainAttachmentName { get; set; }
        public byte[] MainAttachmentBinary { get; set; }
        public string MimeCode { get; set; }
        public string SenderPosition { get; set; }
        public string SenderName { get; set; }
        public string SenderSurname { get; set; }
        public int SenderOrganizationId { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverSurname { get; set; }
        public string ReceiverPosition { get; set; }
        public int ReceiverOrganizationId { get; set; }
        public string AttachmentDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Status { get; set; }
        public string AcceptId { get; set; }
        public string FileSize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentAttachment> DocumentAttachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentProcess> DocumentProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentReference> DocumentReference { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual Organization Organization1 { get; set; }
    }
}
