//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.API.DGA.MIL.DOC.TEST.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentReference
    {
        public int Id { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public Nullable<int> DocumentInId { get; set; }
        public string ReferenceBookNo { get; set; }
        public string ReferenceBookDate { get; set; }
        public string ReferenceBookSubject { get; set; }
        public string State { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual DocumentIn DocumentIn { get; set; }
    }
}
