//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.API.DGA.MIL.DOC.DataAccesLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DGAMilDocEntities : DbContext
    {
        public DGAMilDocEntities()
            : base("name=DGAMilDocEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocumentAttachment> DocumentAttachment { get; set; }
        public virtual DbSet<DocumentReference> DocumentReference { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<Document> Document { get; set; }
        public virtual DbSet<DocumentIn> DocumentIn { get; set; }
        public virtual DbSet<DocumentProcess> DocumentProcess { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
