//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.API.DGA.MIL.DOC.DataAccesLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentProcess
    {
        public int Id { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public string ProcessId { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> DocumentInId { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual DocumentIn DocumentIn { get; set; }
    }
}
